# Generated by Django 4.1.3 on 2022-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/'),
        ),
    ]
