# Generated by Django 4.1.3 on 2022-12-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_kategori_berita_kategori_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='kategori',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
