# Generated by Django 4.1.3 on 2022-12-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_kategori_slug_alter_kategori_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='kategori_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategory', to='news.kategori'),
        ),
    ]
