# Generated by Django 4.1.3 on 2022-12-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_berita_kategori_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='kategori_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.kategori'),
        ),
    ]
