# Generated by Django 4.1.3 on 2022-12-09 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namakapal', models.CharField(max_length=150)),
                ('pemilik', models.CharField(max_length=150)),
                ('nahkoda', models.CharField(max_length=150)),
                ('sipi', models.CharField(max_length=150)),
                ('masa_berlaku', models.DateField()),
                ('abklokal', models.IntegerField()),
                ('abkasing', models.IntegerField()),
                ('bobot', models.IntegerField()),
                ('panjang', models.FloatField()),
                ('dk', models.FloatField()),
                ('tandaselar', models.CharField(max_length=150)),
                ('alattangkap', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HasilTangkap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daerahpenangkapan', models.CharField(max_length=150)),
                ('wpp', models.IntegerField()),
                ('tanggalberangkat', models.DateField()),
                ('tanggaldatang', models.DateField()),
                ('bondolan', models.IntegerField()),
                ('cumi', models.IntegerField()),
                ('etem', models.IntegerField()),
                ('japuh', models.IntegerField()),
                ('kuniran', models.IntegerField()),
                ('layang', models.IntegerField()),
                ('selar', models.IntegerField()),
                ('tembang', models.IntegerField()),
                ('tongkol', models.IntegerField()),
                ('teri', models.IntegerField()),
                ('tengkek', models.IntegerField()),
                ('kapal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.kapal')),
            ],
        ),
    ]
