# Generated by Django 4.1.3 on 2022-12-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kapal',
            old_name='abkasing',
            new_name='abk_asing',
        ),
        migrations.RenameField(
            model_name='kapal',
            old_name='abklokal',
            new_name='abk_lokal',
        ),
        migrations.RenameField(
            model_name='kapal',
            old_name='alattangkap',
            new_name='alat_tangkap',
        ),
        migrations.RenameField(
            model_name='kapal',
            old_name='namakapal',
            new_name='nama_kapal',
        ),
        migrations.RenameField(
            model_name='kapal',
            old_name='tandaselar',
            new_name='tanda_selar',
        ),
    ]
