# Generated by Django 4.1.3 on 2022-12-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_rename_abkasing_kapal_abk_asing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasiltangkap',
            old_name='daerahpenangkapan',
            new_name='daerah_penangkapan',
        ),
        migrations.RenameField(
            model_name='hasiltangkap',
            old_name='tanggalberangkat',
            new_name='tanggal_berangkat',
        ),
        migrations.RenameField(
            model_name='hasiltangkap',
            old_name='tanggaldatang',
            new_name='tanggal_datang',
        ),
    ]
