# Generated by Django 4.1.3 on 2022-12-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_adminrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peta', models.TextField(max_length=40)),
                ('folder', models.FileField(upload_to='peta/')),
            ],
        ),
    ]
