# Generated by Django 4.1.3 on 2022-12-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_peta'),
    ]

    operations = [
        migrations.AddField(
            model_name='peta',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
