# Generated by Django 4.1.3 on 2022-12-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_peta_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesanKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pesan', models.EmailField(max_length=254)),
                ('name_pesan', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
